stages:
  - test

bats_tests:
  stage: test
  image:
    name: bats/bats:latest
    entrypoint: [""]
  script:
    - printenv
    - bats --formatter junit /builds/develop/shell-scripts/tests
  artifacts:
    when: always
    paths:
      - test-results.yml
