stages:
  - test

variables:
  TEST_RESULTS_FILE: test-results.xml

bats_tests:
  stage: test
  image:
    name: bats/bats:latest
    entrypoint: [ "" ]
  script:
    - bats --formatter junit "$PWD/tests" > $TEST_RESULTS_FILE || (exit_code=$?; echo "Bats exit code is $exit_code"; exit $exit_code)
  artifacts:
    when: always
    paths:
      - $PWD/$TEST_RESULTS_FILE
    reports:
      junit: $PWD/$TEST_RESULTS_FILE