stages:
  - test

variables:
  TEST_RESULTS_FILE: test-results.xml

bats_tests:
  stage: test
  image:
    name: bats/bats:latest
    entrypoint: [""]
  script:
    - bats --formatter junit "$PWD/tests" > $TEST_RESULTS_FILE
  artifacts:
    when: always
    paths:
      - $TEST_RESULTS_FILE
    reports:
      junit: $TEST_RESULTS_FILE