stages:
  - test

variables:
  TEST_RESULTS_FILE: test-results.xml

bats_tests:
  stage: test
  image:
    name: bats/bats:latest
    entrypoint: [""]
  script:
    - set +o pipefail
    - bats --formatter junit "$PWD/tests" > $PWD/$TEST_RESULTS_FILE
    - echo "Exit code is $?"
  artifacts:
    when: always
    paths:
      - $PWD/$TEST_RESULTS_FILE
    reports:
      junit: $PWD/$TEST_RESULTS_FILE